# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macos-latest'

stages:

  - stage: CodeQuality
    displayName: 'Check Code Quality'
    jobs:
      - job: RunLint
        displayName: 'Run Lint & Publish Reports'
        steps:
          - task: Gradle@2
            displayName: 'Run Android Lint'
            inputs:
              gradleWrapperFile: 'gradlew'
              tasks: 'lint'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              jdkArchitectureOption: 'x64'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Lint reports'
            condition: succeededOrFailed()
            inputs:
              path: 'app/build/reports/lint-results-debug.html'
              artifact: 'LintReport'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              jdkArchitectureOption: 'x64'

      - job: RunDetekt
        displayName: 'Run Detekt & Publish Reports'
        steps:
          - task: Gradle@2
            displayName: 'Run Detekt'
            inputs:
              gradleWrapperFile: 'gradlew'
              tasks: 'detekt'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              jdkArchitectureOption: 'x64'
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Detekt reports'
            condition: succeededOrFailed()
            inputs:
              path: 'app/build/reports/detekt/detekt.html'
              artifact: 'DetektReport'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              jdkArchitectureOption: 'x64'


  - stage: UnitTest
    displayName: 'Run Unit Tests Stage'
    jobs:
      - job: UnitTest
        displayName: 'Run Unit Tests Job'
        steps:
          - task: Gradle@2
            displayName: 'Unit Tests Task'
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'clean test'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              jdkArchitectureOption: 'x64'


  - stage: AssembleDebug
    displayName: 'Assemble Debug Stage'
    jobs:
      - job: AssembleDebug
        displayName: 'Assemble Debug Job'
        steps:
        - task: Gradle@2
          displayName: 'Assemble Debug Task'
          inputs:
            gradleWrapperFile: 'gradlew'
            tasks: 'assembleDebug'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '11'
            jdkArchitectureOption: 'x64'